<?php
return array (
  9 => 
  array (
    'catid' => '9',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '0',
    'parentid' => '0',
    'arrparentid' => '0',
    'child' => '0',
    'arrchildid' => '9',
    'catname' => '测试',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => '',
    'catdir' => '',
    'url' => 'http://localhost/yuncms/',
    'items' => '1',
    'hits' => '0',
    'setting' => '{"ishtml":"0","content_ishtml":"0","create_to_html_root":"0","template_list":"","meta_title":"","meta_keywords":"","meta_description":"","presentpoint":"1","defaultchargepoint":"0","paytype":"0","repeatchargedays":"1","category_ruleid":"","show_ruleid":""}',
    'listorder' => '9',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'ceshi',
    'usable_type' => '',
    'create_to_html_root' => '0',
    'ishtml' => '0',
    'content_ishtml' => '0',
    'category_ruleid' => '',
    'show_ruleid' => '',
    'workflowid' => NULL,
    'isdomain' => '0',
    'topparentid' => '9',
  ),
  10 => 
  array (
    'catid' => '10',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '0',
    'parentid' => '0',
    'arrparentid' => '0',
    'child' => '0',
    'arrchildid' => '10',
    'catname' => '电脑',
    'style' => '',
    'image' => '',
    'description' => '电脑',
    'parentdir' => '',
    'catdir' => '',
    'url' => 'http://localhost/yuncms/',
    'items' => '0',
    'hits' => '0',
    'setting' => '{"ishtml":"0","content_ishtml":"0","create_to_html_root":"0","template_list":"","meta_title":"","meta_keywords":"","meta_description":"","presentpoint":"1","defaultchargepoint":"0","paytype":"0","repeatchargedays":"1","category_ruleid":"","show_ruleid":""}',
    'listorder' => '10',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'diannao',
    'usable_type' => '',
    'create_to_html_root' => '0',
    'ishtml' => '0',
    'content_ishtml' => '0',
    'category_ruleid' => '',
    'show_ruleid' => '',
    'workflowid' => NULL,
    'isdomain' => '0',
    'topparentid' => '10',
  ),
);
?>